#!/bin/bash

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon 
    python /home/rock/WeOn/src/weon_daemon_interface.py start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python /home/rock/WeOn/src/weon_daemon_interface.py stop
    ;;
  restart)
    echo "Restarting server"
    python /home/rock/WeOn/src/weon_daemon_interface.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /home/rock/WeOn/src/weon_daemon_interface.py {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
